export enum PET_TYPES {
  CAT_MALE = 'CAT_MALE',
  CAT_FEMALE = 'CAT_FEMALE',
}

export enum PET_REPRODUCTION_TYPES {
  STERILIZED = 'STERILIZED',
  NOT_STERILIZED = 'NOT_STERILIZED',
  NEUTERED = 'NEUTERED',
  NOT_NEUTERED = 'NOT_NEUTERED',
}
